version: '3'
services:
    app:
     image: app-for-k8s-test-image
     container_name: kafka-k8s-test-container
     ports:
        - 8091:8091
     networks:
        - net
networks:
   net:
    driver: bridge
