apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-deployment
  labels:
    app: k8s-deployment
spec:
 containers:
   - name: k8s-test
     image: tizor/app-for-k8s-test:1
     ports:
     - containerPort: 80
 
